version: "3.9"

services:
  quiz_service:
    build: ./services/quiz_service
    container_name: quiz_service
    ports:
      - "8000:8000"
    networks:
      - micro_net
    
  chatbot_service:
    build: ./services/chatbot_service
    container_name: chatbot_service
    ports: 
      - "8001:8001"
    env_file:
      - .env
    networks:
      - micro_net

networks:
  micro_net:
    driver: bridge
